#!/bin/bash
# Skrypt usuwa pliki które się wskaże, jeśli pliki nie istnieją nie wyświetla komunikatu o błędzie
# Napisałem, żeby skorzystać w makefilach 
while [ "$1" != "" ]; do
	echo "Jeśli to odpali to, a ja tego nie usunę to mogę się kiedyś zdziwić."
	if [ -f "$1" ]; then 
		rm $1;
	fi 
    	shift
done
